development:
  adapter: mysql2
  database: formTest_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: formTest_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: formTest_production
  username: root
  password: 
  encoding: utf8